### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by olivesdad**
add Instructor controller to add assignments, modify assignment name, and delete assignment

add Junit test for add assignment (WIP)

### CODE REVIEW

**Comment by itsOwlbit** [comment]
Was there a purpose for the StudentController?  I see your InstructorController is the one you built.  Were you able to add the configuration for the JUnit Library?  I am not certain on what is happening with your unit test.
The story doesn't indicate if a return type is needed or not, so I can't really make a suggestion on it.
The controller LGTM.

**Comment by itsOwlbit** [comment]
If you don't want your spring datasource password showing, you can make sure not to push your  application.properties to github.

**Review by olivesdad — COMMENTED** [review]
ok

**Comment by olivesdad** [comment]
Merge and close

**Pull request merged**
